name: build-release
on:
  push: 
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
      - name: cleanup
        run: rm -rf eslint.json rollup.config.js yarn.lock source test
      - name: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
